[LlamaCppOutlines_CPU]
git-tree-sha1 = "989cdf879f6f7436ee22520a41e99398da2f7247"
lazy = true

    [[LlamaCppOutlines_CPU.download]]
    url = "https://github.com/krishnaveti/LlamaCppOutlines.jl/releases/download/v1.0.0/LlamaCppOutlines.v1.0.0.x86_64-w64-mingw32.tar.gz"
    sha256 = "cc94eb1fb9b61fb7882341fe36552a2872ff74b36d0c801716bc2152037bbb12"

    [LlamaCppOutlines_CPU.target.x86_64-w64-mingw32]

[LlamaCppOutlines_GPU]
git-tree-sha1 = "b1c2d3e4f5g6789012345678901234567890bcde"
lazy = true

    [[LlamaCppOutlines_GPU.download]]
    url = "https://github.com/krishnaveti/LlamaCppOutlines.jl/releases/download/v1.0.0/LlamaCppOutlines.v1.0.0.x86_64-w64-mingw32-cuda+12.9.tar.gz"
    sha256 = "7502bf0cacfbd4eddb8358bc680e11daf5eb4be47bac6fd5ec163ee8901db3f9"

    [LlamaCppOutlines_GPU.target."x86_64-w64-mingw32-cuda+12.9"]
